### ISSUE TITLE
Impliment `.connect()`

### ISSUE THREAD

**Issue by deg4uss3r** [rust-cli/clap-port-flag#14]
Right now we are implimenting `.bind()` which is great for opening a local port, but we should consider also allowing a user to call `.connect()` when passing in a port for the connection to a remote server. 

For example: 
`ssh -p 1234 10.42.42.1`

**Comment by yoshuawuyts** [comment]
@deg4uss3r Oh, that's a new angle I hadn't thought about. Just going to dump some thoughts here:

1. All the documentation up until this point has been about managing ports on the local machine. I was thinking this crate should be excellent at figuring out which port to listen to for a service or similar.
2. I'm not entirely sure what the `.connect()` method would do that's different from `.listen()`. I'm guessing the return type? What would that be?
3. Perhaps there is room to have a different crate to pass options for remote connections? I don't know what options might be needed, but it might be good to experiment with that in a separate crate?

Hope this makes sense!

**Comment by deg4uss3r** [comment]
Thanks for responding @yoshuawuyts! 

1. Me too! I like where this crate is going and can't wait to have an excuse to use it :) 
2. Yeah, `.connect()`[1] will return a `Result<TcpStream>` with a connection to the remote server, rather than `.bind()`[2] which returns `Result<TcpListener>`.
3. It is possible! I think it might make sense to throughly explore using this crate since it seems like it would definitely fit, the question is can we do it elegantly? 

I know things are ramping up before August, so we can shelf this until that surge is over. 

[1]: https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect
[2]: https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.bind

**Comment by yoshuawuyts** [comment]
> Yeah, .connect()1 will return a Result<TcpStream> with a connection to the remote server, rather than .bind()2 which returns Result<TcpListener>.

Ahh okay, gotcha. Getting a better picture of what it's for now!

I don't feel strongly about this feature. For me there would be 4 requirements to accept this:
1. There's a concrete use case for this feature right now. (I think we have this).
2. Adding this feature will not lead to require more flags be added down the line. (I don't know the parameters on this one; never used the `TcpStream` API)
3. There's a way to write clear documentation for the flags that covers both versions.
4. All settings & flags that currently exist will be relevant for this version too. (`$LISTEN_FD` for example).

I feel like we'd need to figure out solutions for all of the requirements above if we were to add this. Hope that makes sense!

**Comment by deg4uss3r** [comment]
Thanks for your response! 

1. Great, I think so too :P 
2. I am not sure there's a way to do this at the current moment, since when you use this crate you'll need to signify a way to say this is a client or server. 
3. I definitely think there is a consise way to document if any deviations need to occur. 
4. I should have some time to experiement with this issue this weekend, otherwise `GOTO` 2 :) 

Thanks for looking!
